import type { Stock, NewsItem } from "@/types/stock"

export const mockStocks: Stock[] = [
  {
    symbol: "NVDA",
    company: "NVIDIA Corporation",
    price: 875.28,
    change: 45.67,
    changePercent: 5.5,
    volume: 28500000,
    avgVolume: 25000000,
    marketCap: 2150000000000,
    float: 2450000000,
    gap: 6.2,
    performance: 12.8,
    sector: "Technology",
    industry: "Semiconductors",
    indicators: [
      { type: "hot", icon: "🔥", label: "Hot Stock", color: "text-red-500" },
      { type: "momentum", icon: "⚡", label: "Strong Momentum", color: "text-yellow-500" },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "TSLA",
    company: "Tesla Inc",
    price: 248.42,
    change: 12.35,
    changePercent: 5.2,
    volume: 45000000,
    avgVolume: 35000000,
    marketCap: 790000000000,
    float: 3160000000,
    gap: 5.8,
    performance: 8.9,
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    indicators: [
      { type: "momentum", icon: "⚡", label: "Strong Momentum", color: "text-yellow-500" },
      { type: "catalyst", icon: "📢", label: "News Catalyst", color: "text-blue-500" },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "AAPL",
    company: "Apple Inc",
    price: 192.53,
    change: 8.21,
    changePercent: 4.5,
    volume: 52000000,
    avgVolume: 48000000,
    marketCap: 2950000000000,
    float: 15300000000,
    gap: 4.8,
    performance: 7.2,
    sector: "Technology",
    industry: "Consumer Electronics",
    indicators: [{ type: "catalyst", icon: "📢", label: "News Catalyst", color: "text-blue-500" }],
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "SOXL",
    company: "Direxion Daily Semiconductor Bull 3X Shares",
    price: 45.67,
    change: 3.21,
    changePercent: 7.6,
    volume: 15200000,
    avgVolume: 12000000,
    marketCap: 1200000000,
    float: 26000000,
    gap: 8.2,
    performance: 15.4,
    sector: "Technology",
    industry: "Semiconductors",
    indicators: [
      { type: "hot", icon: "🔥", label: "Hot Stock", color: "text-red-500" },
      { type: "momentum", icon: "⚡", label: "Strong Momentum", color: "text-yellow-500" },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "BBIG",
    company: "Vinco Ventures Inc",
    price: 2.45,
    change: 0.67,
    changePercent: 37.6,
    volume: 8500000,
    avgVolume: 2100000,
    marketCap: 145000000,
    float: 59000000,
    gap: 42.1,
    performance: 28.9,
    sector: "Communication Services",
    industry: "Entertainment",
    indicators: [
      { type: "hot", icon: "🔥", label: "Hot Stock", color: "text-red-500" },
      { type: "catalyst", icon: "📢", label: "News Catalyst", color: "text-blue-500" },
    ],
    lastUpdated: new Date().toISOString(),
  },
  {
    symbol: "MULN",
    company: "Mullen Automotive Inc",
    price: 1.23,
    change: 0.18,
    changePercent: 17.1,
    volume: 12400000,
    avgVolume: 8900000,
    marketCap: 89000000,
    float: 72000000,
    gap: 19.3,
    performance: 11.2,
    sector: "Consumer Cyclical",
    industry: "Auto Manufacturers",
    indicators: [
      { type: "momentum", icon: "⚡", label: "Strong Momentum", color: "text-yellow-500" },
      { type: "risk", icon: "⚠️", label: "High Risk", color: "text-orange-500" },
    ],
    lastUpdated: new Date().toISOString(),
  },
]

export const mockNews: NewsItem[] = [
  {
    id: "1",
    title: "NVIDIA Reports Record Q4 Earnings, Beats Expectations",
    summary: "NVIDIA exceeded analyst expectations with strong data center revenue growth...",
    url: "#",
    source: "MarketWatch",
    publishedAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    sentiment: "positive",
    relatedSymbols: ["NVDA"],
  },
  {
    id: "2",
    title: "Tesla Announces New Gigafactory in Mexico",
    summary: "Tesla reveals plans for a new manufacturing facility to boost production capacity...",
    url: "#",
    source: "Reuters",
    publishedAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    sentiment: "positive",
    relatedSymbols: ["TSLA"],
  },
  {
    id: "3",
    title: "Apple Stock Rises on Strong iPhone Sales",
    summary: "Apple sees increased demand for latest iPhone models in key markets...",
    url: "#",
    source: "Bloomberg",
    publishedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    sentiment: "positive",
    relatedSymbols: ["AAPL"],
  },
]
