name: Push AI Scores
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 13-20 * * 1-5"   # optional: every 5 min 13:00–20:59 UTC, Mon–Fri
env:
  APP_URL: "https://YOUR-APP.vercel.app"   # <- replace with your deployed URL
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Build scores JSON (demo — replace with your model output)
        run: |
          cat > scores.json <<'JSON'
          {
            "generatedAt": null,
            "scores": [
              { "ticker": "ABCD", "score": 0.74, "gap_pct": 6.2, "rvol": 3.1, "rsi14m": 58, "price": 3.45, "volume": 1234567 }
            ]
          }
          JSON

      - name: POST scores to API (uses repo secret)
        run: |
          curl -sS -X POST "$APP_URL/api/scores" \
            -H "content-type: application/json" \
            -H "x-api-key: ${{ secrets.SCORES_API_KEY }}" \
            --data @scores.json
