name: Push AI Scores
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 13-20 * * 1-5"
env:
  APP_URL: "https://v0-finviz-gapper.vercel.app"   # <-- replace with your URL
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Build scores JSON (demo)
        run: |
          cat > scores.json <<'JSON'
          {
            "generatedAt": null,
            "scores": [
              { "ticker": "BLNE", "score": 0.82, "gap_pct": 32.0, "rvol": 5.6, "rsi14m": 61, "price": 3.30, "volume": 1500000 }
            ]
          }
          JSON
      - name: POST scores
        run: |
          curl -sS -X POST "$APP_URL/api/scores" \
            -H "content-type: application/json" \
            -H "x-api-key: ${{ secrets.SCORES_API_KEY }}" \
            --data @scores.json
