name: Push AI Scores

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 13-20 * * 1-5"   # every 5 min during 13:00–20:59 UTC, Mon–Fri

permissions:
  contents: write   # needed to push back to the repo

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ⬇️ Replace this step with your real model pipeline that creates today_scores.json
      - name: Build scores JSON (demo)
        run: |
          mkdir -p public
          cat > public/today_scores.json <<'JSON'
          {
            "generatedAt": null,
            "scores": [
              { "ticker": "ABCD", "score": 0.74, "gap_pct": 6.2, "rvol": 3.1, "rsi14m": 58, "price": 3.45, "volume": 1234567 }
            ]
          }
          JSON

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/today_scores.json
          if git diff --quiet --cached; then
            echo "No changes to commit."
          else
            git commit -m "chore: update today_scores.json"
            git push
          fi
