name: Sync pnpm lockfile

on:
  workflow_dispatch:        # allow manual run from Actions tab
  push:
    paths:
      - "package.json"      # auto-run when package.json changes

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install to update lockfile
        run: pnpm install

      - name: Commit updated lockfile (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pnpm-lock.yaml
          if git diff --cached --quiet; then
            echo "No lockfile changes."
          else
            git commit -m "chore: update pnpm-lock.yaml"
            git push
          fi
